version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: sts-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sts
      POSTGRES_PASSWORD: sts_dev_password
      POSTGRES_DB: stock_taking
    ports:
      - "5433:5432"
    volumes:
      - sts_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: sts-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - sts_redis_data:/data

volumes:
  sts_postgres_data:
  sts_redis_data:


  # changed port from 5432 to 5433
  # running command - docker compose up -d
